### PR TITLE
Development

### PR DESCRIPTION
**Pull request by EmirVatric**

### CODE REVIEW

**Comment by jofer86** [comment]
# Pull Request Under Review By Jorge F. (TSE)

**Comment by mcrd25** [comment]
> # Pull Request Under Review By Jorge F. (TSE)

Good idea! because there is no way to tell if someone else already reviewed it.

Share this on slack so we can all start doing this from now on so there is no mixup

**Comment by jofer86** [comment]
# Hello Emir :wave: :wave: , I'm Jorge, and I will be reviewing this project.

Right from the start, your project looks fantastic it is a nice replica of the original site all in all **Kudos for that** :clap: :clap: .

Now onto the review section..

As far as The Odin Project Requirements go, it seems you did a fine job there.

Now we move onto the guidelines Microverse asks for this particular project, I will go through one by one and leave them here in this comment so that you can have something to reference in case changes are needed to be made.

---

# Minimum Requirements Checklist

To consider the project 'complete' it must satisfy the following points:

### Project Specification Shortcut

#### Mobile \[Screen `width` up to `480px`\]

##### Navigation Bar

:warning:  It is wrapped around a pair of `<nav>` HTML tags. **In this case, your navigation is wrapped around a `<div>`tag, just a minor fix there to keep things semantically correct  :smiley:**
:heavy_check_mark: It has the Newsweek logo on the leftmost part of the navbar
:heavy_check_mark: It has the following icons in the listed order on the rightmost part of the navbar
:heavy_check_mark: Sign in
:heavy_check_mark: Subscribe
:heavy_check_mark: Hamburger menu icon (three horizontal bars)
## Great job on this section, just a minor change to be made. :hand: 
##### Top Story

:warning: It is wrapped by a pair of opening and closing `<section>` HTML tags **While this section it is in fact wrapped in a `<section>` , the more stories section is also contained within the same, please make a different one for each of the sections**
:heavy_check_mark:  It contains a story wrapped by a pair of opening and closing `<article>` HTML tags and a `width` of `100%` ** While the `<article>` for this part does not have a  **
:heavy_check_mark:  From top to bottom, the story has an image, a title and a small paragraph

##### More Stories

:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags heavy_check_mark: It has a header with the text: `More Stories`

###### Articles

:heavy_check_mark: It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning: Each article has a `width` property with a value of `100%` **The articles do not have this CSS property setup  please do the necessary arrangements to meet this requirement**
:heavy_check_mark:  Each article has an image on the leftmost part and a title on the top right corner
:warning:  Each article has a short paragraph in the bottom part. It has a `width` property with a value of `100%` **No width CSS property found on the paragraphs kindly make the required changes**

##### Featured Stories

 :heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark:  It has a header with the text: `Featured Stories`

###### Articles

:heavy_check_mark: It has seven articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning: Each article has a `width` property with a value of `100%` **Here we are missing the width property, kindly fix**
:warning: Each article has a top part with an image. The image has a `width` property with a value of `100%` **In this case what you have is an image with a max width of 100% lets make the proper change**
:warning: Each article has a middle part with an paragraph and a title. Both the paragraph and the title have a `width` property with a value of `100%` **While they do have the required elements both of them lack the width property, please make the adequate changes**

##### Opinion

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags ** I will mark this as a good one even though the section overextends a bit and includes the ads**
:heavy_check_mark: It has a header with the text: `Opinion`

###### Articles

:heavy_check_mark:  It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags **Guidelines say eight but its actually six so its :+1: **
:warning:  Each article has a `width` property with a value of `100%` **No width property on these elements please do make the changes**
:heavy_check_mark: Each article has an image, a title, and an author
:warning: The image should have a `float` property with a value of `left` **Images are not floated, please adjust**
:warning: The title should have a `float` property with a value of `left` **Please do float to the left this too**
:heavy_check_mark:  The title has the author's name underneath

##### Latest News
## :warning: :warning: Could not seem to find this section on your site :warning: :warning:
*** [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags
* [ ] It has a header with the text: `Latest News`

###### Articles

* [ ] It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
* [ ] Each article has a `width` property with a value of `100%`
* [ ] Each article has an image with a `float` property set with a value of `left`
* [ ] Each article's image has a `width` property with a value of `50%`
* [ ] Each article has a title with a `float` property set with a value of `right`
* [ ] Each article's title has a `width` property with a value of `50%`**

##### In the Magazine

:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark: It has a header with the text: `In the Magazine`
:heavy_check_mark: It has the Newsweek logo

###### Articles

:heavy_check_mark: It has seven articles wrapped by a pair of opening and closing `<article>` HTML tags ** This articles are divided in two sections please make it just one **
:heavy_check_mark: .Each article has a `width` property with a value of `100%`
:heavy_check_mark:Each article has an image in the top section
:heavy_check_mark:Each article's image has a `width` property with a value of `100%`
:heavy_check_mark: Each article has a category and a title aligned to the left and below the image

##### Editor's picks

:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark: It has a header with the text: `Editor's picks`
:heavy_check_mark: It has the Newsweek logo

###### Articles

:heavy_check_mark: It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags  **This eight articles are in two sections please make it just one**
:heavy_check_mark:  Each article has a `width` property with a value of `100%`
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%`
:warning: Each article has a middle part with an paragraph and a title. Both the paragraph and the title have a `width` property with a value of `100%` **No width on both of them and the title is an anchor, i can suggest to nest the anchor inside an H2 tag maybe**

##### Featured Slideshow

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark: It has a header with the text: `Featured Slideshow`
:heavy_check_mark: It has the Newsweek logo

###### Articles

:heavy_check_mark:  It has six articles wrapped by a pair of opening and closing `<article>` HTML tags **These are in two `<section>` tags please make them one**
:heavy_check_mark: Each article has a `width` property with a value of `100%`
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%`
:heavy_check_mark:  Each article has a middle part with a title. The title has a `width` property with a value of `100%` ** Same suggestions as above **

##### Footer

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<footer>` HTML tags
:heavy_check_mark: It has a top and a bottom section
:heavy_check_mark:  The top part has the Newsweek logo and social media icons underneath
:heavy_check_mark: The bottom part has an unordered list with a list of links

## This concludes the Mobile section of the review, one thing to note in this part is that when the screen is at 480px up to 1274px, we get a horizontal scroll bar at the bottom, which means that some elements are overflowing the width of the size, meaning that they are over 100%, this is something that I will kindly ask of you to take care of, maybe with making the changes regarding the width on some of the elements to be set at 100% will fix it.

#### Medium \[Screen `width` from `768px` to `1024px`\]

## One thing to note here is that we are starting to get problems with the display in the `768px` size we get some overlapping text on the images in the opinion section. also in the more stories section. And Mostly on the things that are at the rightmost part of the site, also in the first few sections your site is divided in three columns while on the original site is only two columns, basically, that's what's causing the issues with the overlapping and some of the warnings I'm gonna point out. These are the major issues I encounter in this screen size.

##### Navigation Bar

:warning: It is wrapped around a pair of `<nav>` HTML tags **Its wrapped around a `<div>` tag**
:heavy_check_mark: It has the Newsweek logo on the leftmost part of the navbar
:heavy_check_mark:  It has the following icons in the listed order on the rightmost part of the navbar
:heavy_check_mark:  Sign in
:heavy_check_mark:  Subscribe
:heavy_check_mark:  Hamburger menu icon (three horizontal bars)

##### Top Story

:warning: It is wrapped by a pair of opening and closing `<section>` HTML tags **It contains more than just the top story section**
:warning:  It contains a story wrapped by a pair of opening and closing `<article>` HTML tags and a `width` of `100%` **Width not set to 100%**
:heavy_check_mark: From top to bottom, the story has an image, a title and a small paragraph
:warning:  This section has a `width` property with a value of `60%` **No width property on the section**
:heavy_check_mark: It is aligned to the right of the main content

##### More Stories

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark:  It has a header with the text: `More Stories`

###### Articles

:heavy_check_mark: It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning: Each article has a `width` property with a value of `100%` **No width set on the `<article>` tag**
:heavy_check_mark: Each article has an image on the leftmost part and a title on the top right corner
:heavy_check_mark: Each article has a short paragraph in the bottom part. It has a `width` property with a value of `100%` 

## This last two checks come with a task to make the text look proper on the small screen size I.E `768px`, please try to make the necessary adjustments.

##### Featured Stories

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark: It has a header with the text: `Featured Stories`

###### Articles

:heavy_check_mark: It has seven articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning: Each article has a `width` property with a value of `100%` **No width property on the tag**
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%` **It has a max-width of 100% lets just make sure it is set to 100% by default**
:warning: Each article has a middle part with a paragraph and a title. Both the paragraph and the title have a `width` property with a value of `100%` **No width set there**
:warning:  This section has a `width` property with a value of `40%` **Section has a max-width of 33%, please do adjust **
:heavy_check_mark: It is aligned to the left of the main content
:heavy_check_mark: It is displayed below the 'Top Story' Section **Ill set this to be a good mark because its not actually bellow**

##### Opinion

## This section should not be presented as the third column in these screen sizes.

:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark: It has a header with the text: `Opinion`

###### Articles

:heavy_check_mark: It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags **It has more than eight but that is because you included the adds so its :+1: **
:warning:  Each article has a `width` property with a value of `100%` **No `width` property set**
:heavy_check_mark:  Each article has an image, a title and an author
:warning: The image should have a `float` property with a value of `left` **No floats present**
:warning:  The title should have a `float` property with a value of `left` **No floats present **
:heavy_check_mark: The title has the author's name underneath
:warning:  This section has a `width` property with a value of `100%` **Section has a max-width of 25%**
:warning: It is displayed below the 'Featured Stories' Section **It is displayed as a third column, please make the necessary adjustments**

##### Latest News
## :warning: :warning: Could not seem to find this section on your site :warning: :warning:
*** [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags
* [ ] It has a header with the text: `Latest News`

###### Articles

* [ ] It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
* [ ] Each article has a `width` property with a value of `100%`
* [ ] Each article has an image with a `float` property set with a value of `left`
* [ ] Each article's image has a `width` property with a value of `50%`
* [ ] Each article has a title with a `float` property set with a value of `right`
* [ ] Each article's title has a `width` property with a value of `50%`
* [ ] This section has a `width` property with a value of `100%`
* [ ] It is displayed below the 'Opinion' Section**

##### In the Magazine
## feature link seems a bit off in comparison with the original site. Please do fix
:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags **It is wrapped in two sections, in the magazin and editors pick  please do fix it**
:heavy_check_mark: It has a header with the text: `In the Magazine`
:heavy_check_mark: It has the Newsweek logo

###### Articles

:heavy_check_mark: t has seven articles wrapped by a pair of opening and closing `<article>` HTML tags
:heavy_check_mark:  Each article has a `width` property with a value of `100%`
:heavy_check_mark: Each article has an image in the top section
:heavy_check_mark: Each article's image has a `width` property with a value of `100%`
:heavy_check_mark:  Each article has a category and a title aligned to the left and below the image
:heavy_check_mark:  This section has a `width` property with a value of `25%` **I'm guessing this part reffers to the width of each article, so it's :+1:  only in the second section the one that contains four articles the one that has 3 has its width to col-md-4**
:warning: It is displayed below the 'Latest News' Section **No lastest news section**
:warning: This section has a `width` property with a value of `100%` **No width set to 100% , please attend that, Although I'm well aware that the `<section>` tag is a block element therefore is 100'% width, I'm following the guidelines but will bring this to the attention of the staff, in the meantime just add the property, please do assume this way of thinkin for every block element that I made the observation of not having a 100% `width` :pray: **
:heavy_check_mark: It is displayed below the 'Opinion' Section

##### Editor's picks

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark:  It has a header with the text: `Editor's picks`
:heavy_check_mark: It has the Newsweek logo

###### Articles

:heavy_check_mark:  It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning:  Each article has a `width` property with a value of `100%` **The websites shows that each article should have a 50% width so please do make that adjustment according to the proportions of the site**
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%`
:warning:  Each article has a middle part with an paragraph and a title. Both the paragraph and the title have a `width` property with a value of `100%` **Same consideration with the block elements, just add the `width` property**
:warning: This section has a `width` property with a value of `50%` **Width is set at 100%, again this is a tad confusing, so lets just make sure that instead of four elements per row we have two, or it's gonna do some crazy stuff to your site**
:heavy_check_mark: It is displayed below the 'In the Magazine' Section

##### Featured Slideshow

* [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags
* [ ] It has a header with the text: `Featured Slideshow`
* [ ] It has the Newsweek logo

###### Articles

:heavy_check_mark: It has six articles wrapped by a pair of opening and closing `<article>` HTML tags
:heavy_check_mark: Each article has a `width` property with a value of `100%`
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%`
:warning:  Each article has a middle part with a title. The title has a `width` property with a value of `100%` **No width set to 100%**
:heavy_check_mark: This section has a `width` property with a value of `33%`
:heavy_check_mark: It is displayed below the 'Editor's Picks' Section

## I gave some lee way over there cause there is some confusing instructions there, the articles have a width of 100% while having a max width of 33%. And the section being only 33% wide does not compute very much

##### Footer

:warning: The top part should have the Newsweek logo floated to left **No floating there**
:warning: The social media icons are floated to the right **No float property here neither**
:warning: The Bottom part should have an unordered list with links floated to the left **No floating there**

#### Large \[Screen `width` from `1024px` and up\]

##### Navigation Bar

##### Navigation Bar

:warning: It is wrapped around a pair of `<nav>` HTML tags **Its wrapped around a `<div>` tag**
:heavy_check_mark: It has the Newsweek logo on the leftmost part of the navbar
:heavy_check_mark:  It has the following icons in the listed order on the rightmost part of the navbar
:heavy_check_mark:  Sign in
:heavy_check_mark:  Subscribe
:heavy_check_mark:  Hamburger menu icon (three horizontal bars)

##### Top Story

:warning: It is wrapped by a pair of opening and closing `<section>` HTML tags **It contains more than just the top story section**
:warning:  It contains a story wrapped by a pair of opening and closing `<article>` HTML tags and a `width` of `100%` **Width not set to 100%**
:heavy_check_mark: From top to bottom, the story has an image, a title and a small paragraph
:warning:  This section has a `width` property with a value of `50%` **No width property on the section**
:heavy_check_mark: It is aligned to the right of the main content

##### More Stories

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark:  It has a header with the text: `More Stories`

###### Articles

:heavy_check_mark: It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning: Each article has a `width` property with a value of `100%` **No width set on the `<article>` tag**
:heavy_check_mark: Each article has an image on the leftmost part and a title on the top right corner
:heavy_check_mark: Each article has a short paragraph in the bottom part. It has a `width` property with a value of `100%` 
:warning: This section has a `width` property with a value of `50%` **No width value set**
:heavy_check_mark: It is aligned to the middle of the main content
:heavy_check_mark:  It is displayed below the 'Top Story' Section

##### Featured Stories

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark: It has a header with the text: `Featured Stories`

###### Articles

:heavy_check_mark: It has seven articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning: Each article has a `width` property with a value of `100%` **No width property on the tag**
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%` **It has a max-width of 100% lets just make sure it is set to 100% by default**
:warning: Each article has a middle part with a paragraph and a title. Both the paragraph and the title have a `width` property with a value of `100%` **No width set there**
:warning:  This section has a `width` property with a value of `25%` **Section has a max-width of 33%, please do adjust **
:heavy_check_mark: It is aligned to the left of the main content


##### Opinion

## This section should not be presented as the third column in these screen sizes.

:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark: It has a header with the text: `Opinion`

###### Articles

:heavy_check_mark: It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags **It has more than eight but that is because you included the adds so its :+1: **
:warning:  Each article has a `width` property with a value of `100%` **No `width` property set**
:heavy_check_mark:  Each article has an image, a title and an author
:warning: The image should have a `float` property with a value of `left` **No floats present**
:warning:  The title should have a `float` property with a value of `left` **No floats present **
:heavy_check_mark: The title has the author's name underneath
:warning:  This section has a `width` property with a value of `100%` **Section has a max-width of 25%**
:heavy_check_mark: It is aligned to the right of the main content

##### Latest News
## :warning: :warning: Could not seem to find this section on your site :warning: :warning:
*** [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags
* [ ] It has a header with the text: `Latest News`

###### Articles

* [ ] It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
* [ ] Each article has a `width` property with a value of `100%`
* [ ] Each article has an image with a `float` property set with a value of `left`
* [ ] Each article's image has a `width` property with a value of `50%`
* [ ] Each article has a title with a `float` property set with a value of `right`
* [ ] Each article's title has a `width` property with a value of `50%`
* [ ] This section has a `width` property with a value of `100%`
* [ ] It is displayed below the 'Opinion' Section**

##### In the Magazine

:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags **It is wrapped in two sections, in the magazin and editors pick  please do fix it**
:heavy_check_mark: It has a header with the text: `In the Magazine`
:heavy_check_mark: It has the Newsweek logo

###### Articles

:heavy_check_mark: t has seven articles wrapped by a pair of opening and closing `<article>` HTML tags
:heavy_check_mark:  Each article has a `width` property with a value of `100%`
:heavy_check_mark: Each article has an image in the top section
:heavy_check_mark: Each article's image has a `width` property with a value of `100%`
:heavy_check_mark:  Each article has a category and a title aligned to the left and below the image
:heavy_check_mark:  This section has a `width` property with a value of `25%` **I'm guessing this part reffers to the width of each article, so it's :+1:  only in the second section the one that contains four articles the one that has 3 has its width to col-md-4**
:warning: It is displayed below the 'Latest News' Section **No lastest news section**


##### Editor's picks

:heavy_check_mark:  It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark:  It has a header with the text: `Editor's picks`
:heavy_check_mark: It has the Newsweek logo

###### Articles

:heavy_check_mark:  It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
:warning:  Each article has a `width` property with a value of `100%` **The websites shows that each article should have a 50% width so please do make that adjustment according to the proportions of the site**
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%`
:warning:  Each article has a middle part with an paragraph and a title. Both the paragraph and the title have a `width` property with a value of `100%` **Same consideration with the block elements, just add the `width` property**
:warning: This section has a `width` property with a value of `25%` **Width is set at 100%, again this is a tad confusing, so lets just make sure that instead of four elements per row we have two, or it's gonna do some crazy stuff to your site**
:heavy_check_mark: It is displayed below the 'In the Magazine' Section

##### Featured Slideshow

:heavy_check_mark: It is wrapped by a pair of opening and closing `<section>` HTML tags
:heavy_check_mark:  It has a header with the text: `Featured Slideshow`
:heavy_check_mark:  It has the Newsweek logo

###### Articles

:heavy_check_mark: It has six articles wrapped by a pair of opening and closing `<article>` HTML tags
:heavy_check_mark: Each article has a `width` property with a value of `100%`
:heavy_check_mark: Each article has a top part with an image. The image has a `width` property with a value of `100%`
:warning:  Each article has a middle part with a title. The title has a `width` property with a value of `100%` **No width set to 100%**
:heavy_check_mark: This section has a `width` property with a value of `33%`
:heavy_check_mark: It is displayed below the 'Editor's Picks' Section

## I gave some lee way over there cause there is some confusing instructions there, the articles have a width of 100% while having a max width of 33%. And the section being only 33% wide does not compute very much

##### Footer

:warning: The top part should have the Newsweek logo floated to left **No floating there**
:warning: The social media icons are floated to the right **No float property here neither**
:warning: The Bottom part should have an unordered list with links floated to the left **No floating there**

## Theres a lot of changes to be made, please kindly attend the observations and re submit, if you have any doubts or complains about some of the observations I made regarding the project guidelines, just let me know and I shall ask the staff, to work around some of the parts that might not seem accurate.

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Nicely done @EmirVatric 👏
You can merge to master now. Good luck with the next project.

**Pull request merged**
